[package]
authors = ["Webb Technologies Inc."]
edition = "2018"
homepage = "https://substrate.dev"
license = "Unlicense"
name = "darkwebb-standalone-runtime"
repository = "https://github.com/webb-tools/darkwebb-substrate/"
version = "0.1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
substrate-wasm-builder = "4.0.0"

[dependencies]
codec = {package = "parity-scale-codec", version = "2.3.0", default-features = false, features = ["derive", "max-encoded-len"]}
hex-literal = {version = '0.3.1', optional = true}
log = {version = "0.4.14", default-features = false}
scale-info = {version = "1.0.0", default-features = false, features = ["derive"]}
serde = {version = "1.0.101", optional = true, features = ["derive"]}
smallvec = "1.6.1"
static_assertions = "1.1.0"

# local dependencies
darkwebb-primitives = { path = "../../primitives", default-features = false, features = ["hashing"] }
common = { path = "../../common", default-features = false }
pallet-hasher = { path = "../../pallets/hasher", default-features = false }
pallet-verifier = { path = "../../pallets/verifier", default-features = false }
pallet-mt = { path = "../../pallets/mt", default-features = false }
pallet-mixer = { path = "../../pallets/mixer", default-features = false }
pallet-anchor = { path = "../../pallets/anchor", default-features = false }
pallet-bridge = { path = "../../pallets/bridge", default-features = false }
pallet-asset-registry = { path = "../../pallets/asset-registry", default-features = false }
pallet-anchor-handler = { path = "../../pallets/anchor-handler", default-features = false }
orml-traits = { path = "../../open-runtime-module-library/traits", default-features = false }
orml-tokens = { path = "../../open-runtime-module-library/tokens", default-features = false }
orml-currencies = { path = "../../open-runtime-module-library/currencies", default-features = false }
pallet-mt-rpc-runtime-api = { path = "../../pallets/mt/rpc/runtime-api", default-features = false }

# Substrate dependencies
sp-api = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
sp-authority-discovery = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
sp-block-builder = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
sp-consensus-babe = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
sp-core = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
sp-inherents = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
sp-io = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
sp-npos-elections = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
sp-offchain = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
sp-runtime = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
sp-session = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
sp-staking = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
sp-std = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
sp-transaction-pool = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
sp-version = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}

frame-benchmarking = {git = "https://github.com/paritytech/substrate", optional = true, default-features = false, branch = "polkadot-v0.9.11"}
frame-election-provider-support = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
frame-executive = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
frame-support = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
frame-system = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
frame-system-benchmarking = {git = "https://github.com/paritytech/substrate", optional = true, default-features = false, branch = "polkadot-v0.9.11"}
frame-system-rpc-runtime-api = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
pallet-assets = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
pallet-authority-discovery = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
pallet-babe = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
pallet-bags-list = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
pallet-bounties = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}

pallet-grandpa = {git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.11"}

pallet-collective = {default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.11"}
pallet-democracy = {default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.11"}
pallet-election-provider-multi-phase = {default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.11"}
pallet-elections-phragmen = {default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.11"}
pallet-im-online = {default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.11"}
pallet-indices = {default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.11"}
pallet-offences = {default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.11"}

pallet-scheduler = {default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.11"}
pallet-staking = {default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.11"}
pallet-staking-reward-curve = {default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.11"}
pallet-treasury = {default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.11"}

pallet-authorship = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
pallet-balances = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
pallet-multisig = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
pallet-proxy = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
pallet-randomness-collective-flip = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
pallet-session = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11", features = [
  "historical",
]}
pallet-sudo = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
pallet-timestamp = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
pallet-transaction-payment = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
pallet-transaction-payment-rpc-runtime-api = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}
pallet-utility = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.11"}

[features]
default = ["std"]
runtime-benchmarks = [
	"hex-literal",
	"sp-runtime/runtime-benchmarks",
	"frame-benchmarking",
	"frame-system-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-hasher/runtime-benchmarks",
	"pallet-verifier/runtime-benchmarks",
	"pallet-mt/runtime-benchmarks",
	"pallet-mixer/runtime-benchmarks",
	"pallet-anchor/runtime-benchmarks",
	"pallet-anchor-handler/runtime-benchmarks",
	"pallet-asset-registry/runtime-benchmarks",
	"pallet-bridge/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",

]

std = [
  "codec/std",
  "scale-info/std",
  "serde",
  "log/std",
  "sp-api/std",
  "sp-std/std",
  "sp-io/std",
  "sp-core/std",
  "sp-runtime/std",
  "sp-version/std",
  "sp-staking/std",
  "sp-offchain/std",
  "sp-session/std",
  "sp-block-builder/std",
  "sp-transaction-pool/std",
  "sp-inherents/std",
  "frame-support/std",
  "frame-executive/std",
  "frame-system/std",
  "frame-system-rpc-runtime-api/std",
  "sp-authority-discovery/std",
  "pallet-assets/std",
  "pallet-authority-discovery/std",
  "pallet-authorship/std",
  "pallet-babe/std",
  "pallet-bags-list/std",
  "pallet-bounties/std",
  "pallet-balances/std",
  "pallet-grandpa/std",
  "pallet-multisig/std",
  "pallet-indices/std",
  "pallet-proxy/std",
  "pallet-randomness-collective-flip/std",
  "pallet-session/std",
  "pallet-sudo/std",
  "pallet-timestamp/std",
  "pallet-transaction-payment/std",
  "pallet-transaction-payment-rpc-runtime-api/std",
  "pallet-utility/std",
  "pallet-collective/std",
  "pallet-democracy/std",
  "pallet-election-provider-multi-phase/std",
  "pallet-elections-phragmen/std",
  "pallet-im-online/std",
  "pallet-offences/std",
  "pallet-staking/std",
  "pallet-scheduler/std",
  "pallet-treasury/std",
  "sp-consensus-babe/std",
  "sp-npos-elections/std",
  "pallet-hasher/std",
  "pallet-verifier/std",
  "pallet-mt/std",
  "pallet-mixer/std",
  "pallet-anchor/std",
  "pallet-bridge/std",
  "pallet-asset-registry/std",
  "pallet-anchor-handler/std",
  "darkwebb-primitives/std",
  "common/std",
	"pallet-mt-rpc-runtime-api/std",
]
